In [28]:
#should be granted request
#sources
#https://www.geeksforgeeks.org/adding-and-subtracting-matrices-in-python/
#https://numpy.org/doc/stable/reference/generated/numpy.ndarray.item.html

#Request of (0,2,0) TO P0
import numpy as np
import sys
class BankersAlgorithm:
    def __init__(self, Aa, Ba, Ca):
        self.Aa = Aa
        self.Ba = Ba
        self.Ca = Ca
        
    def DeadLockCheck(self, allo, maxR):
        need = np.subtract(maxR, allo)
        numRows = need.shape[0]
        #print(need)
        r = 0
        c = 0 
        for i in range(numRows):
            if self.Aa >= need.item(r,c):
                if self.Ba >= need.item(r,c+1):
                    if self.Ca >= need.item(r,c+2):
                        if not np.array_equal(need[r], [0, 0, 0]):
                            print('process ',r,' can run')
                            self.Aa = self.Aa + allo.item(r,c)
                            self.Ba = self.Ba + allo.item(r,c+1)
                            self.Ca = self.Ca + allo.item(r,c+2)
                            allo[r] = [0,0,0]
                            max[r] = [0,0,0]
                            need[r] = [0,0,0]
                            print('updated need matrix')
                            print(need)
                            print('updated resource amounts')
                            print(self.Aa, self.Ba, self.Ca)
                            self.DeadLockCheck(allo, maxR)
                        else:
                            print('process ',r, 'doesn\'t need to run')
                    else:
                        print('process ',r, ' cannot run')
                else:
                   print('process ',r, ' cannot run') 
            else:
                print('process ',r, ' cannot run')
            if r <= 5:   
                r = r + 1
                #print('row number is ', r)
            if r == 5:
                print('algorithm is complete. These processes are deadlock free')
                sys.exit(0)
                
    def IsOverNeed(self, req, allo, maxR):
        need = np.subtract(maxR, allo)
        print(need)
        if req.item(RequestProcessRow,0) > need.item(RequestProcessRow,0):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        elif req.item(RequestProcessRow,1) > need.item(RequestProcessRow,1):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        elif req.item(RequestProcessRow,2) > need.item(RequestProcessRow,2):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        else:
            print('request is not greater than the need')

    def CanItRun(self, allo, maxR):
        need = np.subtract(maxR, allo)
        print(need)
        numRows = need.shape[0]
        RunCounter = 0
        for i in range(numRows):
            if need.item(i,0) > self.Aa and need.item(i,1) > self.Ba and need.item(i,2) > self.Ca:
                RunCounter = RunCounter +1
                print('runcounter ', RunCounter)
            print('i = ', i)
            
        print('Number of processes that could run = ', RunCounter)

        if RunCounter == 0:
            print('Not enough resources. Not safe')
            sys.exit(0)

request = np.array([[0,2,0],
                   [0,0,0],
                   [0,0,0],
                   [0,0,0],
                   [0,0,0]])

#Resources
alloPreRequest = np.array([[0,1,0],
                          [2,0,0],
                          [3,0,2],
                          [2,1,1],
                          [0,0,2]])

allocation = np.add(request,alloPreRequest)

max = np.array([[7,5,3],
               [3,2,2],
               [9,0,2],
               [2,2,2],
               [4,3,3]])

#available vectors
Aa = 3
Ba = 1
Ca = 2
RequestProcessRow = 0

banker_object = BankersAlgorithm(Aa, Ba, Ca)
banker_object.CanItRun(allocation, max)
banker_object.IsOverNeed(request, alloPreRequest, max)
banker_object.DeadLockCheck(allocation, max)

[[7 2 3]
 [1 2 2]
 [6 0 0]
 [0 1 1]
 [4 3 1]]
runcounter  1
i =  0
i =  1
i =  2
i =  3
i =  4
Number of processes that could run =  1
[[7 4 3]
 [1 2 2]
 [6 0 0]
 [0 1 1]
 [4 3 1]]
request is not greater than the need
process  0  cannot run
process  1  cannot run
process  2  cannot run
process  3  can run
updated need matrix
[[7 2 3]
 [1 2 2]
 [6 0 0]
 [0 0 0]
 [4 3 1]]
updated resource amounts
5 2 3
process  0  cannot run
process  1  can run
updated need matrix
[[7 2 3]
 [0 0 0]
 [6 0 0]
 [0 0 0]
 [4 3 1]]
updated resource amounts
7 2 3
process  0  can run
updated need matrix
[[0 0 0]
 [0 0 0]
 [6 0 0]
 [0 0 0]
 [4 3 1]]
updated resource amounts
7 5 3
process  0 doesn't need to run
process  1 doesn't need to run
process  2  can run
updated need matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [4 3 1]]
updated resource amounts
10 5 5
process  0 doesn't need to run
process  1 doesn't need to run
process  2 doesn't need to run
process  3 doesn't need to run
process  4  can run
updated need ma

SystemExit: 0

In [17]:
#should be Denied because of lack of resources
#sources
#https://www.geeksforgeeks.org/adding-and-subtracting-matrices-in-python/
#https://numpy.org/doc/stable/reference/generated/numpy.ndarray.item.html

#Request of (3,3,0) TO P4
import numpy as np
import sys
class BankersAlgorithm:
    def __init__(self, Aa, Ba, Ca):
        self.Aa = Aa
        self.Ba = Ba
        self.Ca = Ca
        
    def DeadLockCheck(self, allo, maxR):
        need = np.subtract(maxR, allo)
        numRows = need.shape[0]
        #print(need)
        r = 0
        c = 0 
        for i in range(numRows):
            if self.Aa >= need.item(r,c):
                if self.Ba >= need.item(r,c+1):
                    if self.Ca >= need.item(r,c+2):
                        if not np.array_equal(need[r], [0, 0, 0]):
                            print('process ',r,' can run')
                            self.Aa = self.Aa + allo.item(r,c)
                            self.Ba = self.Ba + allo.item(r,c+1)
                            self.Ca = self.Ca + allo.item(r,c+2)
                            allo[r] = [0,0,0]
                            max[r] = [0,0,0]
                            need[r] = [0,0,0]
                            print('updated need matrix')
                            print(need)
                            print('updated resource amounts')
                            print(self.Aa, self.Ba, self.Ca)
                            self.DeadLockCheck(allo, maxR)
                        else:
                            print('process ',r, 'doesn\'t need to run')
                    else:
                        print('process ',r, ' cannot run')
                else:
                   print('process ',r, ' cannot run') 
            else:
                print('process ',r, ' cannot run')
            if r <= 5:   
                r = r + 1
                #print('row number is ', r)
            if r == 5:
                print('algorithm is complete. These processes are deadlock free')
                sys.exit(0)
                
    def IsOverNeed(self, req, allo, maxR):
        need = np.subtract(maxR, allo)
        print(need)
        if req.item(RequestProcessRow,0) > need.item(RequestProcessRow,0):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        elif req.item(RequestProcessRow,1) > need.item(RequestProcessRow,1):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        elif req.item(RequestProcessRow,2) > need.item(RequestProcessRow,2):
            print('Request denied. Request is greater than need. \n')
            sys.exit(0)
        else:
            print('request is not greater than the need')

    def CanItRun(self, allo, maxR):
        need = np.subtract(maxR, allo)
        print(need)
        numRows = need.shape[0]
        RunCounter = 0
        for i in range(numRows):
            if need.item(i,0) > self.Aa and need.item(i,1) > self.Ba and need.item(i,2) > self.Ca:
                RunCounter = RunCounter +1
                print('runcounter ', RunCounter)
            print('i = ', i)
            
        print('Number of processes that could run = ', RunCounter)

        if RunCounter == 0:
            print('Not enough resources. Not safe')
            sys.exit(0)
        
request = np.array([[0,0,0],
                   [0,0,0],
                   [0,0,0],
                   [0,0,0],
                   [3,3,0]])

#Resources
alloPreRequest = np.array([[0,1,0],
                          [2,0,0],
                          [3,0,2],
                          [2,1,1],
                          [0,0,2]])

allocation = np.add(request,alloPreRequest)

max = np.array([[7,5,3],
               [3,2,2],
               [9,0,2],
               [2,2,2],
               [4,3,3]])

#available vectors
Aa = 0
Ba = 0
Ca = 2
RequestProcessRow = 4

banker_object = BankersAlgorithm(Aa, Ba, Ca)
banker_object.CanItRun(allocation, max)
banker_object.IsOverNeed(request, alloPreRequest, max)
banker_object.DeadLockCheck(allocation, max)

Number of processes that could run =  0
Not enough resources. Not safe


SystemExit: 0